version: '3.8'
services:
  cats-app:
    build: /cats
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://user:password@mongo-db:27017/
  dogs-app:
    build: /dogs
    ports:
      - "6000:6000"
    depends_on:
      - db
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password