apiVersion: skaffold/v2beta29
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: cats
      context: cats
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - ./k8s/*